// front-end/react/src/views/content/work/projects/index.js
import React, { PureComponent } from 'react';
import styled from 'styled-components';

import ProjectPanel from './projectPanel';
import ProjectView from './projectView';

import projects from '../../../../data/static/projects';

const ProjectsWrapper = styled.div`
  display: grid;
  grid-template-columns: 25% 75%;
`;

export default class Projects extends PureComponent {

  state = {
    selectedProject: null,
    projects: projects
  };

  handleSelect = (project) => {
    this.setState({ selectedProject: project });
  };

  render() {

    const { selectedProject } = this.state;

    return (
      <ProjectsWrapper>
        <ProjectPanel
          projects={projects}
          selected={selectedProject}
          onSelect={this.handleSelect}
        />
        <ProjectView
          project={selectedProject}
        />
      </ProjectsWrapper>
    );
  }

}

// front-end/vue/src/components/elements/Projects.vue

<template>
  <div class="projects">
      <ProjectPanel
        :projects="projects"
        :selected="selectedProject"
        :onSelect="handleSelect"
      />
      <ProjectView
        :project="selectedProject"
      /> 
  </div>
</template>

<script>

import ProjectPanel from './ProjectPanel.vue';
import ProjectView from './ProjectView.vue';

import projects from '../../content/projects.js';

export default {
  components: {
    ProjectPanel, ProjectView
  },
  data() {
    return {
      projects,
      selectedProject: null
    };
  },
  methods: {
    handleSelect(project) {
      this.selectedProject = project;
    },
  }
};

</script>

<style scoped lang="postcss">

.projects {
  display: grid;
  grid-template-columns: 25% 75%;
}

</style>
