// front-end/vue/src/components/elements/ProjectSearch.vue
<template>
  <form id="search-input">
    <label for="query">search all projects</label>
    <input
      v-model="query"
      @keyup="handleFilterChange"
      name="query" 
      id="query" 
      type="text" 
    >
    <label for="sort">sort by</label>
    <select 
      v-model="sort" 
      v-on:change="handleSortChange"
    >
      <option value="{ 'key':'date', 'direction': -1 }">Date: New to Old</option>
      <option value="{ 'key':'date', 'direction': 1 }">Date: Old to New</option>
      <option value="{ 'key':'title', 'direction': 1 }">Title: A to Z</option>
      <option value="{ 'key':'title', 'direction': -1 }">Title: Z to A</option>
    </select>
  </form>
</template>

<script>


export default {
  props: {
    onSort: Function,
    onFilter: Function
  },
  data() {
    return {
      sort: ['date', 1],
      query: ''
    };
  },
  methods: {
    handleSortChange() {
      const { key, direction } = JSON.parse(this.sort.replace(/'/g, '"'));
      this.onSort({ key, direction });
    },
    handleFilterChange() {
      const filter = {
        query: this.query,
      };
      this.onFilter(filter);
    }
  }

};

</script>

<style scoped lang="postcss">

label {
  display: block;
}

select {
  background-color: var(--white);
}


</style>

// front-end/react/src/views/content/work/projects/projectPanel/ProjectSearch.js
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const ProjectSearchWrapper = styled.form`

  label {
    display: block;
  }

  select {
    background-color: ${ ({ theme }) => theme.white};
  }

`;

export default class ProjectSearch extends PureComponent {

  static propTypes = {
    onSort: PropTypes.func.isRequired,
    onFilter: PropTypes.func.isRequired,
  };

  state = {
    sort: 'dateNewOld',
    query: ''
  };

  onChange = e => this.setState({ [e.target.name]: e.target.value });

  handleSortChange = async(e) => {
    await this.onChange(e);
    this.props.onSort(this.state.sort);
  };

  handleFilterChange = async(e) => {
    await this.onChange(e);
    const filter = {
      query: this.state.query,
    };
    this.props.onFilter(filter);
  };

  render() {

    const { query, sort } = this.state;
    const { sortOptions } = this.props;

    const optionList = Object.keys(sortOptions).map(key => {
      return <option key={key} value={key}>{sortOptions[key].title}</option>;
    });

    return (
      <ProjectSearchWrapper>

        <label htmlFor="query">search all projects</label>
        <input
          type="text"
          name="query"
          value={query}
          onChange={this.handleFilterChange}
        />
        <label htmlFor="sort">sort by</label>
        <select
          name="sort"
          value={sort}
          onChange={this.handleSortChange}
        >
          {optionList}
        </select>
      </ProjectSearchWrapper>
    );
  }
}
