// front-end/vue/src/components/elements/ProjectCard.vue
<template>
  <li
    :class="{ selected: project === selected }"
    @click="handleClick"
  >
    <span>{{ project.title }}</span>
    <p>{{ project.summary }}</p>
  </li>
</template>

<script>


export default {

  props: {
    project: Object,
    selected: Object,
    onSelect: Function
  },
  methods: {
    handleClick() {
      this.onSelect(this.project);
    }
  }

};

</script>

<style scoped lang="postcss">

.selected {
  background-color: var(--darkgreen);
}


</style>

// react-redux-full/src/views/content/work/projects/projectPanel/projectList/ProjectCard.js
import React from 'react';
import styled from 'styled-components';

const ProjectCardWrapper = styled.li`
  list-style: none;
  border-bottom: 1px solid black;

  background-color: ${ ({ theme, selected }) => {
    return selected ? theme.darkgreen : theme.white;
  }};

  span {
    font-weight: bolder;
  }

  &:hover {
    background-color: ${ ({ theme }) => theme.lightgreen};
    cursor: pointer;
  }
`;

const ProjectCard = ({ project, selected, onSelect }) => {

  const handleClick = () => {
    onSelect(project);
  };

  return (
    <ProjectCardWrapper
      selected={selected}
      onClick={handleClick}
    >
      <span>{project.title}</span>
      <p>{project.summary}</p>
    </ProjectCardWrapper>
  );

};

export default ProjectCard;
